#!/usr/bin/env sh

echo '🏗️👷 Running checks on your code before committing' 🔍🧐

echo "styling your work" 🎨✨


# Check Prettier standards
pnpm run check-format || {
    echo '🤢🤮🤢🤮 Its so ugly!! - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Running npm run format...'
    npm run format
    git add .
    echo '✨ Formatting complete and changes staged. Please re-run your commit to include the fixes.'
    exit 1
}


echo '🏗️👷 checking for eslint errors' 🔍🧐

# Check ESLint Standards
pnpm run lint ||
	(
		echo '😤🏀👋😤 Get that beans code out of here! 😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
		false
	)

echo '🏗️👷 checking for typescript errors' 🔍🧐

# Check tsconfig standards
pnpm run check-types ||
	(
		echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
           Are you seriously trying to write that? Make the changes required above.'
		false
	)

# npx lint-staged       

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'

echo '✅✅ Awesome work! ✅✅'
echo '🚀⛅ Run git push to upload your changes to the remote repository ⛅🚀'